### ISSUE TITLE
Consulta por licencia

### ISSUE THREAD

**Issue by dajuarez** [bitDubai/competition#7]
Hola @competition-team, les queria consultar ya que he creado un archivo de licencia en el siguiente directorio  competition/2016AUC/lincense-agreements/

y no veo que aparezca el archivo creado cuando vuelvo a entrar al repositorio en otro momento

gracias.

**Comment by Luis-Fernando-Molina** [comment]
Hola, lo que pasa que lo has creado en tu fork. Tenes que enviarlo desde ahí hacia el repo de bitDubai. 

Acá podés tener un poco de ayuda si no sabés como se hace: https://github.com/bitDubai/fermat/blob/master/README-GIT.md

cualquier cosa, avisá.

Saludos!

**Comment by gustl-arg** [comment]
license created succesfully.
